title: Musings of a Robot
description: "Developer by day...and sometimes night.  Thoughts on development, life, development, and getting by."
locale: en_US
url: //cody1024d.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Cody Duncan
  email: cody1024d@gmail.com
  bio: "Live life to the fullest...and code sometimes."
  avatar: bioPhoto.jpg # 160x160 px image for author byline
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
